package com.xkorey.myibatis.dao;

import com.xkorey.myibatis.models.FunLog;

public interface FunLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fun_log
     *
     * @mbg.generated Sun Apr 02 00:24:32 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fun_log
     *
     * @mbg.generated Sun Apr 02 00:24:32 CST 2017
     */
    int insert(FunLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fun_log
     *
     * @mbg.generated Sun Apr 02 00:24:32 CST 2017
     */
    int insertSelective(FunLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fun_log
     *
     * @mbg.generated Sun Apr 02 00:24:32 CST 2017
     */
    FunLog selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fun_log
     *
     * @mbg.generated Sun Apr 02 00:24:32 CST 2017
     */
    int updateByPrimaryKeySelective(FunLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fun_log
     *
     * @mbg.generated Sun Apr 02 00:24:32 CST 2017
     */
    int updateByPrimaryKeyWithBLOBs(FunLog record);
}