package com.xkorey.myibatis.models;

public class FunLog {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fun_log.id
     *
     * @mbg.generated Sun Apr 02 00:24:32 CST 2017
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fun_log.info
     *
     * @mbg.generated Sun Apr 02 00:24:32 CST 2017
     */
    private String info;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fun_log.id
     *
     * @return the value of fun_log.id
     *
     * @mbg.generated Sun Apr 02 00:24:32 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fun_log.id
     *
     * @param id the value for fun_log.id
     *
     * @mbg.generated Sun Apr 02 00:24:32 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fun_log.info
     *
     * @return the value of fun_log.info
     *
     * @mbg.generated Sun Apr 02 00:24:32 CST 2017
     */
    public String getInfo() {
        return info;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fun_log.info
     *
     * @param info the value for fun_log.info
     *
     * @mbg.generated Sun Apr 02 00:24:32 CST 2017
     */
    public void setInfo(String info) {
        this.info = info;
    }
}